version: 0.2

env:
  variables:
    key: "value"
    key: "value"

phases:
  install:
    commands:
      - sh ./scripts/install.sh
  pre_build:
    commands:
      - sh ./scripts/pre_build.sh
  post_build:
    commands:
      - sh ./scripts/post_build.sh
artifacts:
  files:
    - '**/**'
  discard-paths: no
